# Application name and server port
spring:
  profiles:
    active: test
  main:
    allow-bean-definition-overriding: true
  application:
    name: Auth
  datasource:
    url: jdbc:postgresql://localhost:5432/Auth
    username: postgres
    password: 0
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


# Server Configuration
server:
  port: 8081


